"""empty message

Revision ID: 738a796c3f0a
Revises: 7a76c257df70
Create Date: 2021-12-13 01:34:21.957994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738a796c3f0a'
down_revision = '7a76c257df70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('privileged', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'privileged')
    # ### end Alembic commands ###