"""empty message

Revision ID: 738a796c3f0b
Revises: 85ece6cfed22
Create Date: 2021-12-13 01:34:21.957994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "738a796c3f0b"
down_revision = "85ece6cfed22"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "services", sa.Column("username", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("services", "username")
    # ### end Alembic commands ###
