"""empty message

Revision ID: 85ece6cfed22
Revises: 738a796c3f0a
Create Date: 2021-12-27 23:08:26.124204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "85ece6cfed22"
down_revision = "738a796c3f0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("services", sa.Column("cache", sa.String(length=12), nullable=True))
    op.drop_column("services", "privileged")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "services",
        sa.Column(
            "privileged",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("services", "cache")
    # ### end Alembic commands ###
