[package]
name = "services_manager_server"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "prisma-cli"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.18.0"

prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.10", default-features = false, features = ["postgresql"] }
serde = { version = "1.0.192", features = ["derive"] }

tokio = { version = "1.33.0", features = ["full"] }
axum = { version = "0.6.20", features = ["json"] }
axum-prometheus = "0.4.0"
chrono = "0.4.31"
sentry = { version = "0.31.7", features = ["debug-images"] }

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"]}
tower-http = { version = "0.4.4", features = ["trace"] }
