[package]
name = "services_manager_server"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "prisma-cli"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.19.0"

prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.10", default-features = false, features = ["postgresql"] }
serde = { version = "1.0.198", features = ["derive"] }

tokio = { version = "1.37.0", features = ["full"] }
axum = { version = "0.7.5", features = ["json"] }
axum-prometheus = "0.6.1"
chrono = "0.4.38"
sentry = { version = "0.32.3", features = ["debug-images"] }

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"]}
tower-http = { version = "0.5.2", features = ["trace"] }
